config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "pages#homepage"

  get "signup" ,to: "users#new"
  resources :users, except: [:new]
  
  get "login" , to: "sessions#new"
  post "login", to: "sessions#create"
  get "logout", to: "sessions#destroy"

  resources :posts
  get "userposts", to:"posts#userposts"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user

    validates :title, 
        presence: true, 
        length: {minimum:1, maximum:100}

    validates :description,
        presence: true,
        length: {minimum:5, maximum:500}

end

app/models/user.rb
class User < ApplicationRecord
    has_many :posts

    validates :username, 
        presence: true, 
        uniqueness: true, 
        length: {minimum:3, maximum:25}

    EMAIL_FORMAT = /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/i
    validates :email, 
        presence: true, 
        uniqueness: true, 
        length: {maximum: 100},
        format: { with: EMAIL_FORMAT }

    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :logged_in?

    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def logged_in?
        !!current_user
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def homepage
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy]

  # GET /posts or /posts.json
  def index
    @posts = Post
      .all
      .order(id: :desc)
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  def userposts
    @posts = Post
      .where(user_id: session[:user_id])
      .order(id: :desc)
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    @post.user_id = session[:user_id]

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :description, :user_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end
    
    def create
        user = User.find_by(username: params[:session][:username])
        if user && user.authenticate(params[:session][:password])
            session[:user_id] = user.id
            flash[:notice] = "Welcome back #{params[:session][:username]}"
            redirect_to root_path
        else
            flash.now[:notice] = "ERROR while logging in"
            render :new
        end
    end

    def destroy
        session[:user_id] = nil
        flash[:notice] = "Logged out successfully"
        redirect_to root_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]


  # GET /users or /users.json
  def index
    @users = User.paginate(page: params[:page], per_page: 5)
  end

  # GET /users/1 or /users/1.json
  def show
  end

  def userposts
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)
    @user.email.downcase!
    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        flash[:notice] = "Account created successfully, welcome #{@user.username}"
        format.html { redirect_to root_path}
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:username, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Friends</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
  </head>

  <header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark pl-2">
      <a class="navbar-brand" href="/">
          <%= image_tag "wakuwaku.jpeg", width: "30" , class:   "rounded"%>
          Friends
      </a>
      
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <% if logged_in?%>
            <li class="nav-item-active">
              <%= link_to "Posts" , "/posts#index",class: "nav-link"%>
            </li>
            <li class="nav-item-active">
              <%= link_to "Users" , "/users#index", class: "nav-link"%>
            </li>

            <li class="nav-item-active">
              <%= link_to current_user.username , userposts_path, class: "nav-link"%>
            </li>

            <li class="nav-item-active">
              <%= link_to "Log Out", logout_path,class: "nav-link"%>
            </li>

          <%else%>
            <li class="nav-item-active">
              <%= link_to "Log In", "login" , class: "nav-link"%>
            </li>

            <li class="nav-item-active">
              <%= link_to "Sign Up", "signup" , class: "nav-link  "%>
            </li>
          <% end %>

          
        </ul>
      </div>
    </nav>
  
  <body>
    <%= yield %>
  </body>

</html>

app/views/pages/homepage.html.erb
<%= flash.notice %>
<h1>Homepage for the app</h1>

app/views/posts/_form.html.erb
<%= render 'shared/errors' , obj: @post%>

<%= form_with(model: post) do |form| %>
  <%= form.text_field :title, type: "string"%>
  <%= form.text_area :description, type: "text"%>
  
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
    <div><%= post.id%></div>
    <div><%= post.title%></div>
    <div><%= post.description%></div>
</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Posts</h1>

<div id="posts">
  <% @posts.each do |post| %>
    <%= render post %>
    <p>
      <%= link_to "Show this post", post %>
    </p>
  <% end %>
</div>

<%= link_to "New post", new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @post %>

<div>
  <%= link_to "Edit this post", edit_post_path(@post) %> |
  <%= link_to "Back to posts", posts_path %>

  <%= button_to "Destroy this post", @post, method: :delete %>
</div>

app/views/posts/userposts.html.erb
<h1>Your Posts</h1>
<%= link_to "New post", new_post_path %>
<div id="posts">
  <% @posts.each do |post| %>
    <%= render post %>
    <% if post.user_id == current_user.id %>  
      <%= button_to "Destroy this post", post, method: :delete %>
    <% end %> 
    
    <p>
      <%= link_to "Show this post", post %>
    </p>
  <% end %>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(obj.errors.count, "error") %> prohibited this <%=obj.class.name.downcase%> from being saved:</h2>

      <ul>
        <% obj.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/users/_form.html.erb
<%= render "shared/errors" , obj:@user%>

<%= form_with(model: user) do |form| %>
  <%= form.text_field :username, type: "string" , placeholder:"Username"%>
  <%= form.email_field :email, type: "string", placeholder:"Email"%>
  <%= form.password_field :password, type: "string", placeholder:"Password"%>
  <div>
    <%= form.submit "Sign Up" , class: "btn btn-primary"%>
  </div>
<%end%>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
    <div><%= user.id%></div>
    <div><%= user.username%></div>
    <div><%= user.email%></div>
    <div><%= user.password%></div>
</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>
<%= link_to "New user", new_user_path %>  

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>
<div class="apple_pagination">  
    <%= will_paginate @users, :container => false %>
</div>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>